src/pollap/apps/website/urls.py
from django.urls import path
from .views import signup

urlpatterns = [
    path('register/', signup, name="signup"),
    
]

src/pollap/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from pollap.apps.website.views import LandingView

urlpatterns = [
    path('', LandingView.as_view(), name="landing"),
    path('website/', include(('pollap.apps.website.urls', 'pollap.apps.website'), namespace='website')),
    path('admin/', admin.site.urls)
]

src/pollap/apps/championships/models.py
from django.db import models

class ChampionshipTemplate(models.Model):
    """Represents an abstract football championship."""
    name = models.CharField(max_length=50)
    size = models.IntegerField(default=2)

    def __str__(self):
        return self.name

class Phase(models.Model):
    name = models.CharField(max_length=50)
    championship = models.ForeignKey(
        ChampionshipTemplate, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Team(models.Model):
    name = models.CharField(default="", max_length=100)
    image = models.ImageField(
        upload_to='teams/')
    

class Championship(models.Model):
    starts = models.DateTimeField(auto_now=False, auto_now_add=False)
    ends = models.DateTimeField(auto_now=False, auto_now_add=False)

    championshipTemplate = models.ForeignKey(
        ChampionshipTemplate, on_delete=models.CASCADE, null=True, blank=True)
    
class RegisteredTeam(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    championship = models.ForeignKey(Championship, on_delete=models.CASCADE)

class Match(models.Model):
    NOT_STARTED = "not started"
    PLAYING = "playing"
    ENDED = "ended"

    player1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='player1_matches')
    player2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='player2_matches')

    player1_goals = models.IntegerField(default=0, null=True, blank=True)
    player2_goals = models.IntegerField(default=0, null=True, blank=True)

    status = models.BooleanField(default=NOT_STARTED)
    
    def __str__(self):
        return "{} vs {}".format(self.player1, self.player2)

src/pollap/apps/website/models.py
from django.db import models

src/pollap/apps/championships/views.py
from django.shortcuts import render

# Create your views here.

src/pollap/apps/website/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView
from django.shortcuts import render, redirect

class LandingView(TemplateView):
    template_name = "website/index.html"


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'website/signup.html', {'form': form})

src/pollap/apps/website/templates/website/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Pollap, bet with your friends</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "website/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "website/css/jumbotron.css" %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Pollap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Language</a>
            <div class="dropdown-menu" aria-labelledby="Language">
              <a class="dropdown-item" href="#">English</a>
              <a class="dropdown-item" href="#">Spanish</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="User" aria-label="User">
          <input class="form-control mr-sm-2" type="password" placeholder="Password" aria-label="Password">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
        </form>
      </div>
    </nav>

    <div>
      {% block content%}
      {% endblock %}
    </div>

    <footer class="container">
      <p>&copy; Company 2017-2018</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="{% static 'website/js/popper.min.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>
  </body>
</html>

src/pollap/apps/website/templates/website/index.html
{% extends "website/base.html" %} 
{% load static %} 
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Pollap!</h1>
    <p> We enjoy to make bets about a football match or championship, so let's create a bet with your friends
    <p>
      <a class="btn btn-primary btn-lg" href="{% url 'website:signup'%}" role="button">Register</a>
    </p>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum
        nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
        </p>
      <p>
        <a class="btn btn-secondary" href="#" role="button">View details &raquo;</a>
      </p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum
        nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
        </p>
      <p>
        <a class="btn btn-secondary" href="#" role="button">View details &raquo;</a>
      </p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod
        semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet
        risus.</p>
      <p>
        <a class="btn btn-secondary" href="#" role="button">View details &raquo;</a>
      </p>
    </div>
  </div>
  <hr>
</div>
<!-- /container -->
{% endblock %}

src/pollap/apps/website/templates/website/signup.html
{% extends "website/base.html" %} 
{% load static %} 
{% block content %}

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-6 col-offset-2">
      <h2>Register</h2>
      <form method="post">
          {% csrf_token %}
          {% for field in form %}
            <p>
              {{ field.label_tag }}<br>
              {{ field }}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </p>
          {% endfor %}
        <input class="btn btn-secondary" type="submit" value="Save" />
      </form>
    </div>
  </div>
  <hr>
</div>
<!-- /container -->
{% endblock %}